[package]
name = "day1"
version = "0.1.0"
authors = ["sum-catnip <catnip@catnip.fyi>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "day1"
path = "src/lib.rs"

[dependencies]
input = { path = "../input" }
