[package]
name = "day9"
version = "0.1.0"
authors = ["sum-catnip <catnip@catnip.fyi>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
input = { path = "../input" }
day1 = { path = "../day1" }
