[package]
name = "day7"
version = "0.1.0"
authors = ["sum-catnip <catnip@catnip.fyi>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
input = { path = "../input" }
regex = "1.4.2"
lazy_static = "1.4.0"
